### ISSUE TITLE
Allow customising what command display in /sign help

### ISSUE THREAD

**Issue by baailey** [Deltik/SignEdit#23]
Currently, the list of commands that are displayed only shows a very limited few that, ideally, I'd prefer to remove from /sign help. But, after looking over the `locales` files, I could not find where a file that allowed me to edit the commands that are displayed.

I suggest introducing a list in the Comms.properties file that allows adding/removing what text is display there. Thanks.

**Comment by Deltik** [comment]
Currently, [the list of `/sign` subcommands is hard-coded](https://github.com/Deltik/SignEdit/blob/v1.12.8/src/org/deltik/mc/signedit/ChatComms.java#L143-L150).

One area of improvement I can think of is to hide subcommands that the player does not have access to use.  Would this be an acceptable solution?

**Comment by baailey** [comment]
That works! Though, it'd also be good to add undo and redo to help?

**Comment by Deltik** [comment]
Yes, I agree that `/sign undo` and `/sign redo` should be added to the usage help.  I think I will have to implement help pagination because the current `/sign help` has maxed out the 10 lines that the Minecraft client will display at once.

**Comment by baailey** [comment]
Either that or you remove the Usage and Online help lines? Even just as a temporary solution?

**Comment by Deltik** [comment]
A similar feature has been implemented in [**SignEdit for Bukkit v1.13.0**](https://github.com/Deltik/SignEdit/releases/tag/v1.13.0), which you can directly download [here](https://github.com/Deltik/SignEdit/releases/download/v1.13.0/SignEdit-1.13.0.jar)!

## Actual Implementation

* `/sign help` will only display usage syntax help for `/sign` subcommands that the player is allowed to use.
* As there are now more subcommands than can fit on one page of chat printing, `/sign help` now takes an additional argument (`/sign help [<page>]`), which is the page number to see more subcommands.
* The "Online Help" line in `/sign help` can be hidden by setting `online_documentation=` (blank it out) in your [locale override](https://github.com/Deltik/SignEdit#custom-translations) file.
* New locale strings:
  * `usage_page_heading` – Styling for the heading of the redesigned `/sign help`
  * `usage_page_info` – Contents of the heading of `/sign help`
  * `usage_page_numbering` – Shows the page number of the `/sign help` page

## Rationale

Instead of free reign for the translator to change the text of `/sign help`, it is less of a maintenance burden to have an opinionated way of displaying `/sign` subcommand usage syntax.
