### ISSUE TITLE
Unnecessary triggering of configuration reload

### ISSUE THREAD

**Issue by oskarkk** [Deltik/SignEdit#29]
The `config.yml` file isn't checked for "modification", but for "change". So doing something like `chmod o+r config.yml` will trigger configuration reload (even if owner already had read permission). I sometimes do `chmod` and `chgrp` on the whole server dir to fix permissions, and also on any backup, and that triggers config reload. Nothing important, but I guess fixing this would be a simple change.

```
$ stat config.yml
  File: config.yml
  Size: 2383            Blocks: 8          IO Block: 4096   regular file
Device: 8,2     Inode: 4077324     Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1003/      mc)   Gid: ( 1003/      mc)
Access: 2021-11-14 21:49:16.134506071 +0100
Modify: 2022-03-26 13:56:21.212597386 +0100
Change: 2022-03-28 14:25:53.067393211 +0200
 Birth: 2021-11-14 21:49:16.134506071 +0100
```

https://unix.stackexchange.com/questions/2802/what-is-the-difference-between-modify-and-change-in-stat-command-context:

> There are 3 kind of "timestamps":
> 
> Access - the last time the file was read
> Modify - the last time the file was modified (content has been modified)
> Change - the last time meta data of the file was changed (e.g. permissions)

Also, I think that this auto-reload should be configurable.

**Comment by Deltik** [comment]
This issue will be fixed for the next release.  Because it's a minor behavior change, I plan to bundle it with the fix for https://github.com/Deltik/SignEdit/issues/28.

By the way, I did not make the configuration file auto-reload configurable because of [my (controversial) design choice where the plugin fully manages the configuration file](https://github.com/Deltik/SignEdit/issues/9#issuecomment-579727798).  Apparently, sysadmins don't like it when configuration files change outside of their control.  I might reconsider this choice in the future, but it's not a priority.  If someone else wants to implement configuration management opt-out, I'll welcome a [pull request](https://github.com/Deltik/SignEdit/pulls).
