### ISSUE TITLE
Conflict with Lockette Pro Plugin

### ISSUE THREAD

**Issue by IAFEnvoy** [Deltik/SignEdit#32]
When i try to use /sign ui on a lock sign create by the Lockette Pro. It can be edited.

But it will cause a ClassCastException on closing the sign edit screen and the sign will be destroyed and dropped.

**Comment by Deltik** [comment]
Heya!  [LockettePro](https://github.com/brunyman/LockettePro) is abandoned and has lingering bugs that I tried to get the author to fix.

The good news is that @rutgerkok's [BlockLocker](https://github.com/rutgerkok/BlockLocker) is a drop-in replacement that is actively supported.  I personally use this plugin in combination with SignEdit for Bukkit and was [involved](https://github.com/rutgerkok/BlockLocker/issues/18#issuecomment-997119027) in fixes to ensure that BlockLocker works with SignEdit for Bukkit.

I encourage you to try switching from LockettePro to BlockLocker.  If this is not an acceptable solution, please let me know, and I can see if there's something that can be done from the side of SignEdit for Bukkit.  Otherwise, I'll leave this issue closed.
