### ISSUE TITLE
Sign did not change

### ISSUE THREAD

**Issue by baailey** [Deltik/SignEdit#35]
After placing a sign and then right clicking it to use the default Minecraft sign edit feature, SignEdit will send a message saying Sign did not change upon entering the UI, and will reset any changes that are made. And upon clicking done to apply the change, it'll send `Player baailey just tried to change non-editable sign` in console.

SignEdit Version: 1.14.0-beta3
Server Version: git-Paper-66 (MC: 1.20.1)

This does not happen on SignEdit Version 1.13.9-beta1 and Server Version git-Paper-47 (MC: 1.20.1)

https://github.com/Deltik/SignEdit/assets/62433969/9fa42c88-1811-48d2-97ba-618da7f24eff

**Comment by Deltik** [comment]
@baailey: Thanks for reporting this bug!

It has _probably_ been fixed in [SignEdit for Bukkit v1.14.0-beta4](https://github.com/Deltik/SignEdit/releases/tag/v1.14.0-beta4), which you can directly download [here](https://github.com/Deltik/SignEdit/releases/download/v1.14.0-beta4/SignEdit-1.14.0-beta4.jar).
