### ISSUE TITLE
Latest signedit version crashes server and spams errors

### ISSUE THREAD

**Issue by SecretlyJealous** [Deltik/SignEdit#37]
After updating to [v1.14.0-beta3](https://www.spigotmc.org/resources/signedit-for-bukkit.47604/update?update=507678) my server spams errors and crashes.

Error spam: https://pastebin.com/hzdEXLQM
Different error spam: https://pastebin.com/7N4Yq1qV
Server not responding: https://pastebin.com/FPiayYgU

**Comment by Deltik** [comment]
This bug will be fixed in the next (pre-)release.  Until then, you can use this snapshot, which has the patch that fixes the bug: [**SignEdit-1.14.0-beta3-1-g79ed0ab-SNAPSHOT.zip**](https://github.com/Deltik/SignEdit/files/12001500/SignEdit-1.14.0-beta3-1-g79ed0ab-SNAPSHOT.zip)

There some other significant bugs that need fixing before I can make another release, though.  Follow https://github.com/Deltik/SignEdit/issues/35 and https://github.com/Deltik/SignEdit/issues/36 to track the release blockers.

**Comment by SecretlyJealous** [comment]
I think for now I'm just going to temporarily remove the plugin, my big concern is how this issue can cause the server to crash

**Comment by Deltik** [comment]
The crash should be fixed by that snapshot.  I'll try to fix the remaining usability issues soon.
