### ISSUE TITLE
Suggestion: copy command

### ISSUE THREAD

**Issue by FabioZumbi12** [Deltik/SignEdit#8]
Hi,

I want to suggest a feature to we copy and paste one sign to other signs with quantity.

Something like:
`/signedit copy` will copy the sign to be pasted one time;
`/signedit copy 5` will copy the sign to be paste for 5 times interacting with other signs;

Is something like the other plugin https://dev.bukkit.org/projects/signedit

Thanks.

**Comment by Deltik** [comment]
A similar function has been implemented in [**SignEdit for Bukkit v1.10.0**](https://github.com/Deltik/SignEdit/releases/tag/v1.10.0)!

## Actual Implementation

- `/signedit copy` copies the targeted sign with no limit to the number of pastes.
- `/signedit paste` pastes whatever was copied onto the targeted sign.

## Rationale

The implementation described above was chosen over the proposed implementation because it's clunky to hold onto a clipboard for a fixed number of pastes.
