### ISSUE TITLE
Implement user-defined custom localization

### ISSUE THREAD

**Issue by Deltik** [Deltik/SignEdit#9]
Request [from the Spigot Forums](https://www.spigotmc.org/threads/signedit.275199/page-2#post-3571825):

> Excellent work. In initial installation, no language/localization files are created (locale:en). How do I customize English language messages?
> ― [SlimeDog](https://www.spigotmc.org/members/slimedog.56363/)

**Comment by SlimeDog** [comment]
Thanks. I look forward to it. No rush though. The default messages are fine for now.

**Comment by Deltik** [comment]
@SlimeDog: The requested feature was introduced in [SignEdit for Bukkit v1.11.0](https://github.com/Deltik/SignEdit/releases/tag/v1.11.0)!

Documentation of the new feature can be found [here](https://github.com/Deltik/SignEdit/blob/v1.11.0/README.md#advanced-customization).

**Comment by SlimeDog** [comment]
I am glad to finally be able to localize the messages, but I do not understand why you have invented such an obscure method for doing so. Localization has been implemented by hundreds (if not thousands) of plugins in very straightforward ways. Oh well, so long as it works.

**Comment by Deltik** [comment]
@SlimeDog: Thank you for the feedback.  Can you explain what you mean by "such an obscure method for [localization]" and/or provide examples of plugins with straightforward localization?  The locale files used by SignEdit are standard [Java resource bundles](https://docs.oracle.com/javase/8/docs/api/java/util/ResourceBundle.html).

----

What I did invent was two isolated directories:

- `./plugins/SignEdit/locales/overrides/` – These are the user-defined locales.  SignEdit won't mess with the user's customizations.
- `./plugins/SignEdit/locales/originals/` – These are a read-only copy of the built-in locale files to which the user can refer to update their customizations.

I chose to let the user take full control of their locale override files because there is no way that an updated SignEdit can anticipate what strings the user has changed and merge appropriately―that requires human intervention.

**Comment by SlimeDog** [comment]
There are a few basic methods in use in the 150 plugins we test.

For most of them, the configuration files are
- ./plugins/PLUGIN_NAME/config.yml
- ./plugins/PLUGIN_NAME/messages.yml
- ./plugins/PLUGIN_NAME/lang/messages_LANGUAGECODE.yml, LANGUAGECODE=en, for example, or a similar coding scheme

There are variations in naming conventions, but the basic principles apply. Some plugins allow individual players to select a language, but that is extremely rare, and not worth exploring further.

For both config.yml and localization files, in order of preference:
- Never modify the configuration files, thereby never overwriting user changes. This required that users merge any changes. The best in this category list all configuration changes (or "no configuration changes") in updates, so that users can merge the changes. My own plugins do this (two entries in our test protocol verify that the files are not overwritten on startup or reload).
- **Merge changes to configuration files by adding new nodes (with default values), while leaving data and comments intact**. The last bit is important; compare with the next bullet. This is the most common practice, despite your contention that "there is no way that an updated SignEdit can anticipate what strings the user has changed and merge appropriately". Of course there is -- you manage the nodes, leaving the values intact.
- Overwrite configuration files, leaving data intact, but eliding comments (except at the top) and blank lines. This is an unfortunate model, but unfortunately somewhat common since it is apparently the simplest API: If all nodes are not accounted for, overwrite the file (sometimes with default values, erasing the users changes).

For localization files specifically, in addition to the above:
- Write new nodes to separate files, and warn in the log that there are new nodes that should be added to the localization files. This is effective, but rare, and requires users to pay attention.

To help explain our preferences, here is a summary of our upgrade process:
- Unzip JAR files to expose the configuration files (default configuration files should always be included in JAR files; if not, then generate them by loading the plugin on an empty test server).
- Save the new configuration files in ./plugins/PLUGIN_DIRECTORY/releases/VERSION_STRING/, so they can be compared with previous versions.
- Compare the new configuration files with the previous version.
- Merge changes to the active configuration files on a test server.
- Test the configuration changes.
- Migrate the changes into production.
- Remove the previous version files.

This process requires more attention and more work on our part, but guarantees that we have the configuration we want. (We also employ test servers, and test plugin updates before deploying them into production, which is apparently somewhat uncommon.)

I hope this information is instructive and helpful.

**Comment by Deltik** [comment]
Thank you for the explanation.  Your upgrade process sounds like a perfectly reasonable workflow to me.

The good news is that SignEdit for Bukkit's localization system behaves exactly like your most preferred configuration file policy.  The user-defined locale files in `./plugins/SignEdit/locales/overrides/` are never modified.  Updated strings are always placed in `./plugins/SignEdit/locales/originals/` for reference so the admin can copy new keys when needed.

Unfortunately, the design choice I made for `./plugins/SignEdit/config.yml` conflicts with your preference.  I did weigh the pros and cons of all three configuration file management strategies and settled on a fully managed configuration file.

----

### Fully Managed `config.yml`

For:

- Quick reference to config options without needing to consult online documentation
- Comment documentation would not become outdated
- Automated migration to new versions

Against:

- Wipes out user comments

### Semi-Managed `config.yml`

For:

- Maintains existing behavior (SignEdit for Bukkit `>= 1.1, < 1.11`)
- Automatically adds missing keys by adding them and their default values

Against:

- Disorganized: Keys may appear in an arbitrary order.
- Comments may become outdated.

### Unmanaged `config.yml`

For:

- Doesn't interfere with configuration management software (e.g. Ansible, Puppet, and SaltStack)
- Easy to downgrade if backwards-incompatible changes are made to the configuration file format

Against:

- Prevents future feature that allows an operator to configure the plugin in-game or from the console (e.g. `/signadmin set line-starts-at 0`, `/signadm set force-locale true`)
- No migration to newer versions that change or add to the configuration file format
- New default values are not added

----

I ruled out the unmanaged strategy because it conflicts with a future convenience feature for a server admin to update the configuration from in-game or from the console.  I switched the strategy from semi-managed to fully-managed in version 1.11.0 to organize the configuration file and maintain a brief updated documentation inside the comments to make it easier for the server admin to configure the plugin by editing the file.

**These changes are meant to reduce the burden on the server admin**, especially as SignEdit for Bukkit gets more features over time.

**Comment by SlimeDog** [comment]
Thank you for approving our workflow.

I appreciate your explanation of the choices made. I would make different choices, but it's your plugin.

Unmanaged does not prevent the (future) convenience feature you describe. Some plugins do exactly that. Losing my comments is not a feature. Still, I like the features with which SignEdit works, and will continue to use it.
